// Generated by scripts/generate-ascet-element-write-contract.mjs. Do not edit.
using System;

public static class AscetElementWriteContract
{
    public const int Version = 2;
    public const string ContractSha256 = "18a544dad3db2e5c5390df7e126991f40bd62ae6c6c49c4e2a3119f5f89d021f";
    public static readonly string[] IntentValues = new string[] { "create", "patch", "upsert", "restore" };
    public static readonly string[] KindValues = new string[] { "variable", "parameter", "array", "enumeration", "table", "component" };
    public static readonly string[] ScopeValues = new string[] { "local", "exported", "imported" };
    public static readonly string[] RoleValues = new string[] { "standardPrimitive", "providerExportedParameter", "consumerImportedParameter", "localDependentParameter", "array", "enumeration", "table", "componentReference" };
    public static readonly string[] RootFields = new string[] { "elements" };
    public static readonly string[] ElementFields = new string[] { "name", "kind", "modelType", "scope", "physicalRange", "length", "enumerationPath", "tableDimension", "xValues", "yValues", "values", "referencedComponentPath", "unit", "comment", "calibration", "configurationProvenance", "data", "impl" };
    public static readonly string[] NormalizedElementFields = new string[] { "name", "kind", "modelType", "scope", "physicalRange", "length", "enumerationPath", "tableDimension", "xValues", "yValues", "values", "referencedComponentPath", "unit", "comment", "calibration", "data", "impl" };
    public static readonly string[] DataFields = new string[] { "value" };
    public static readonly string[] ImplementationFields = new string[] { "memoryLocation", "valueType", "implementationRange", "formula", "limitAssignments" };
    public static readonly string[] RangeFields = new string[] { "min", "max" };
}
