import type { AscetActionInstruction } from "./types.ts";

export const ascetEditInstructions = [
	{
		id: "ascet_edit.preflight",
		tool: "ascet_edit",
		action: "preflight",
		profiles: ["write-preflight"],
		summary: "Default write behavior is preflight; execute only when explicitly requested.",
		rules: [
			"By default this tool returns a non-error preflight outcome and does not write.",
			"Set executeWrite=true only when the user explicitly asks to apply the write; PI still requires confirmation.",
			"Use verifyReadback=true unless the user explicitly asks to skip readback.",
			"When component kind is unknown, inspect the target before executeWrite=true.",
		],
		fewShots: ['preflight: ascet_edit({action:"create_folder",folderPath:"DEMO/New",verifyReadback:true})'],
		tags: ["write", "preflight", "safety"],
	},
	{
		id: "ascet_edit.create_component",
		tool: "ascet_edit",
		action: "create_component",
		profiles: ["write-preflight"],
		summary: "Create folder/component targets with kind-specific defaults and readback.",
		rules: [
			"After create_component, inspect expectedDefaultScaffold.defaultEntryMethod as an unverified hint for the likely initial method.",
			'For create_component, kind may be class, module, statemachine, or enumeration. Only class and module need language; enumeration uses ASCET intrinsic language and usually reads back languageKind="Unknown".',
		],
		fewShots: [
			'create_component: ascet_edit({action:"create_component",componentPath:"DEMO/C",kind:"class",language:"ESDL",verifyReadback:true})',
		],
		tags: ["write", "component"],
	},
	{
		id: "ascet_edit.method_edit",
		tool: "ascet_edit",
		action: "method_edit",
		profiles: ["write-preflight"],
		summary: "Create and edit methods according to component kind and signature requirements.",
		rules: [
			"Before create_method, determine the target component kind. In v1, methodKind is constrained by component kind: class supports only abstract; module supports only process; statemachine supports only action, condition, or trigger.",
			"When methodKind is omitted for create_method, componentKind=class defaults to abstract and componentKind=module defaults to process. For statemachine targets, choose action, condition, or trigger explicitly.",
			"Do not create class methods with methodKind=process/action/condition/trigger. For ESDL Class components, create abstract first, then use set_method_signature for return/arguments and set_method_code for the body. Do not claim the method is concrete unless readback proves MethodKind changed.",
			"Use set_method_signature after create_method and before method body writes when the method body returns a value or reads method arguments; do not use apply_element_spec for method return or argument declarations.",
			"Use set_method_signature.arguments for primitive method inputs before writing ESDL code that references them, and verify readback.",
		],
		fewShots: [
			'set_method_signature: ascet_edit({action:"set_method_signature",componentPath:"DEMO/PID",methodName:"calc",returnType:"cont",arguments:[{name:"u",type:"cont",ifExists:"replace"}]})',
		],
		tags: ["write", "method", "signature"],
	},
	{
		id: "ascet_edit.code_edit",
		tool: "ascet_edit",
		action: "code_edit",
		profiles: ["write-preflight"],
		summary: "Write method, module, or state-machine code only through the matching action surface.",
		rules: [
			"For method bodies on Class or Module components, use set_method_code.",
			"Use set_module_code only for module text-code surfaces such as set-method, set-header, or set-external-c-code.",
			"For set_module_code, provide section/operation as one of set-method, set-header, or set-external-c-code.",
			"For set_state_machine_code, use one of: set-method, set-state-entry-esdl, set-state-exit-esdl, set-state-static-esdl, bind-state-entry-method, bind-state-exit-method, bind-state-static-method, set-transition-condition-esdl, set-transition-action-esdl, bind-transition-condition-method, bind-transition-action-method, set-start-state.",
		],
		fewShots: [
			'set_method_code: ascet_edit({action:"set_method_code",componentPath:"DEMO/PID",methodName:"calc",codeFile:"calc.esdl",verifyReadback:true})',
		],
		tags: ["write", "code"],
	},
	{
		id: "ascet_edit.apply_element_spec",
		tool: "ascet_edit",
		action: "apply_element_spec",
		profiles: ["write-preflight"],
		summary: "Apply structured primitive element specs from evidence, not guesses.",
		rules: [
			"For apply_element_spec, treat specFile as a structured ASCET element-spec JSON artifact, not just a file path.",
			"Start from the element's code role and explicit requirements: determine whether it is a parameter, variable, array, state, or enumeration, how the code reads or writes it, its domain, lifecycle, and initialization intent. That semantic intent drives the target spec; do not let a similarly named element or a read result replace the code-level meaning.",
			"Then use public evidence to resolve the ASCET representation and current state: use ascet_search.search_elements or ascet_search.text_in_code for discovery, ascet_read.read_code for complete code, and ascet_read.read_dependent_chain when dependency context matters. If the action schema or result fields are unclear, call ascet_capabilities.search_actions first. Do not guess modelType, scope, range, implementation type, formula, calibration, or dependency.",
			"For a new element, treat code semantics and explicit requirements as the source of desired values; treat live reads as compatibility and preservation evidence. For an existing element, preserve all unchanged live fields and emit only the requested patch. Do not copy a sibling element's values unless semantic equivalence is established.",
			"For apply_element_spec primitive elements, variable/parameter/array specs must include name, kind, modelType, and scope. Use concrete modelType values such as cont, log, sdisc, or udisc; do not use ambiguous disc.",
			"For apply_element_spec, mode=restore updates/restores the supplied spec but does not remove missing elements unless deleteMissing=true is set.",
			"For apply_element_spec, physicalRange and impl.implementationRange are mutually exclusive. Choose exactly one range source per element; do not put both in the same spec element.",
			"Dependency is not part of apply_element_spec JSON. To make a parameter dependent, call set_element_dependency after the target parameter exists.",
			"Method return values and method arguments are not apply_element_spec elements. For method return or arguments such as calc/p_CmpF_MC1, use set_method_signature before writing method code.",
			"Use verifyReadback=true for apply_element_spec unless the user explicitly asks to skip verification.",
			"If required primitive fields are unknown, stop at preflight and inspect the live component or ask for the missing field; do not write a partial specFile.",
		],
		fewShots: [
			'apply_element_spec: ascet_edit({action:"apply_element_spec",componentPath:"DEMO/PID",specFile:"spec.json",mode:"restore",verifyReadback:true})',
		],
		tags: ["write", "element"],
	},
	{
		id: "ascet_edit.dependent_parameter",
		tool: "ascet_edit",
		action: "dependent_parameter",
		profiles: ["write-preflight"],
		summary: "Write dependent local parameters only after exported-provider evidence is resolved.",
		rules: [
			"Before creating or updating a dependent Local Parameter, resolve the authoritative same-named Exported Parameter provider with read_dependent_chain or the coordinated read/search/explore workflow.",
			"Do not bind to a provider candidate unless the matching element is scope=Exported.",
			"If the exported counterpart is unknown, ambiguous, or not found, stop at preflight and gather provider evidence before writing.",
			"The Imported Parameter and Exported Parameter must have the same name. The Local Dependent Parameter may differ, but its formula mapping must resolve through Imported Parameter names.",
			"When creating a dependent Local Parameter from an Exported Parameter, align metadata from the Exported Parameter, not from the Imported Parameter, unless the user explicitly requests a transform.",
			"Imported Parameters are bridge elements and normally require no independent implementation configuration. Do not invent implementation range, formula, calibration, or limits for Imported Parameters unless project rules explicitly require it.",
			"Do not create an exported parameter inside the consuming component merely to satisfy a dependency relationship.",
			"Use set_element_dependency to set or clear the dependency flag of an existing local parameter and to set that local parameter's dependency formula.",
			"set_element_dependency does not create local, imported, or exported elements. Use apply_element_spec first when any of those elements are missing.",
			"dependencyFormula is the expression stored on the dependent local parameter. It is not an implementation conversion formula and is not a project formula.",
			'When dependencyFormula is provided, pass dependency="dependent". Do not pass dependencyFormula together with dependency="independent".',
			"Referenced imported parameters must already exist in the consuming component. Do not create imported parameters, exported parameters, or provider components inside set_element_dependency.",
			"After a successful executed set_element_dependency write, PI refreshes element_decls and full_element_cache from live read_element_catalog readback; if refresh fails, follow index.issues.",
		],
		fewShots: [
			'set_element_dependency: ascet_edit({action:"set_element_dependency",targetPath:"F/C",elementName:"K",dependency:"dependent",verifyReadback:true})',
		],
		tags: ["write", "dependency", "provider-discovery"],
	},
	{
		id: "ascet_batch_write.batch_write",
		tool: "ascet_batch_write",
		action: "batch_write",
		profiles: ["batch-write"],
		summary: "Hidden batch-write instruction.",
		rules: [
			"Batch write is hidden by default and must not be injected into public prompt assembly unless explicitly enabled.",
		],
		hidden: true,
		tags: ["hidden", "batch"],
	},
] as const satisfies readonly AscetActionInstruction[];
