import type { AscetActionInstruction } from "./types.ts";

export const ascetEditInstructions = [
	{
		id: "ascet_edit.preflight",
		tool: "ascet_edit",
		action: "preflight",
		profiles: ["write-preflight"],
		summary: "Default write behavior is preflight; execute only when explicitly requested.",
		rules: [
			"By default this tool returns a non-error preflight outcome and does not write.",
			"Set executeWrite=true only when the user explicitly asks to apply the write; PI still requires confirmation.",
			"Executed writes always perform mandatory automatic action-specific readback verification. Inspect the returned verification feedback and do not issue a redundant live read after verification passes.",
			"When component kind is unknown, inspect the target before executeWrite=true.",
		],
		fewShots: ['preflight: ascet_edit({action:"create_folder",folderPath:"DEMO/New"})'],
		tags: ["write", "preflight", "safety"],
	},
	{
		id: "ascet_edit.create_component",
		tool: "ascet_edit",
		action: "create_component",
		profiles: ["write-preflight"],
		summary: "Create folder/component targets with kind-specific defaults and automatic verification.",
		rules: [
			"After create_component, inspect expectedDefaultScaffold.defaultEntryMethod as an unverified hint for the likely initial method.",
			'For create_component, kind may be class, module, statemachine, or enumeration. Only class and module need language; enumeration uses ASCET intrinsic language and usually reads back languageKind="Unknown".',
		],
		fewShots: [
			'create_component: ascet_edit({action:"create_component",componentPath:"DEMO/C",kind:"class",language:"ESDL"})',
		],
		tags: ["write", "component"],
	},
	{
		id: "ascet_edit.method_edit",
		tool: "ascet_edit",
		action: "method_edit",
		profiles: ["write-preflight"],
		summary: "Create and edit methods according to component kind and signature requirements.",
		rules: [
			"Before create_method, determine the target component kind. In v1, methodKind is constrained by component kind: class supports only abstract; module supports only process; statemachine supports only action, condition, or trigger.",
			"When methodKind is omitted for create_method, componentKind=class defaults to abstract and componentKind=module defaults to process. For statemachine targets, choose action, condition, or trigger explicitly.",
			"Do not create class methods with methodKind=process/action/condition/trigger. For ESDL Class components, create abstract first, then use set_method_signature for return/arguments and set_method_code for the body. Do not claim the method is concrete unless readback proves MethodKind changed.",
			"Use set_method_signature after create_method and before method body writes when the method body returns a value or reads method arguments; do not use apply_element_spec for method return or argument declarations.",
			"Use set_method_signature.arguments for primitive method inputs before writing ESDL code that references them, then inspect the automatic action-specific readback verification.",
		],
		fewShots: [
			'set_method_signature: ascet_edit({action:"set_method_signature",componentPath:"DEMO/PID",methodName:"calc",returnType:"cont",arguments:[{name:"u",type:"cont",ifExists:"replace"}]})',
		],
		tags: ["write", "method", "signature"],
	},
	{
		id: "ascet_edit.code_edit",
		tool: "ascet_edit",
		action: "code_edit",
		profiles: ["write-preflight"],
		summary: "Write method, module, or state-machine code only through the matching action surface.",
		rules: [
			"For method bodies on Class or Module components, use set_method_code.",
			"Use set_module_code only for module text-code surfaces such as set-method, set-header, or set-external-c-code.",
			"For set_module_code, provide section/operation as one of set-method, set-header, or set-external-c-code.",
			"For set_state_machine_code, use one of: set-method, set-state-entry-esdl, set-state-exit-esdl, set-state-static-esdl, bind-state-entry-method, bind-state-exit-method, bind-state-static-method, set-transition-condition-esdl, set-transition-action-esdl, bind-transition-condition-method, bind-transition-action-method, set-start-state.",
		],
		fewShots: [
			'set_method_code: ascet_edit({action:"set_method_code",componentPath:"DEMO/PID",methodName:"calc",codeFile:"calc.esdl"})',
		],
		tags: ["write", "code"],
	},
	{
		id: "ascet_edit.apply_element_spec",
		tool: "ascet_edit",
		action: "apply_element_spec",
		profiles: ["write-preflight"],
		summary: "Apply structured primitive element specs from evidence, not guesses.",
		rules: [
			"For apply_element_spec, call phase=plan with intent=create|patch|upsert|restore and inline role-discriminated elements. specFile is internal and must not be supplied by the model; commit accepts only phase=commit plus planId.",
			"Start from the element's code role and explicit requirements: determine whether it is a parameter, variable, array, state, or enumeration, how the code reads or writes it, its domain, lifecycle, and initialization intent. That semantic intent drives the target spec; do not let a similarly named element or a read result replace the code-level meaning.",
			"Then use public evidence to resolve the ASCET representation and current state: use ascet_get.tree and ascet_get.elements for bounded discovery, then Pi find/grep/read for stored observations; use ascet_read.read_code for complete code and ascet_read.read_dependent_chain only for exact dependency detail. If the action schema or result fields are unclear, call ascet_capabilities.search_actions first. Do not guess modelType, scope, range, implementation type, formula, calibration, or dependency.",
			"For a new element, treat code semantics and explicit requirements as the source of desired values; treat live reads as compatibility and preservation evidence. For an existing element, preserve all unchanged live fields and emit only the requested patch. Do not copy a sibling element's values unless semantic equivalence is established.",
			"Provider Exported Parameter creation requires explicit unit, comment, calibration, range, data, and implementation decision groups. Use range.mode=none|physical|implementation, data.mode=explicit|ascetDefault, and implementation.mode=explicit|ascetDefault; omission is invalid and values must come from evidence.",
			"Local Dependent Parameter creation requires explicit unit, comment, calibration, range, and implementation decision groups, but forbids data because its value comes from Dependency binding. Imported Parameter is the lightweight exception and must not contain data, implementation, range, or calibration. Existing-element patches may omit unchanged fields.",
			"For implementation.mode=explicit, provide valueType, memoryLocation, formula, and limitAssignments. Use an empty formula to explicitly select no conversion formula and null limitAssignments when that option is not applicable. Ranged discrete Parameters require limitAssignments=true.",
			"Use the role-specific element contract. standardPrimitive create requires name, kind, modelType, and scope; provider/imported/dependent roles supply or derive their fixed parameter kind/scope. Patch may contain only changed fields because plan merges the live snapshot.",
			"For intent=restore, provide a complete inline restoration spec. deleteMissing and recreateIncompatible are destructive controls and must be visible in the plan before commit.",
			"For apply_element_spec, physicalRange and impl.implementationRange are mutually exclusive. Choose exactly one range source per element; do not put both in the same spec element.",
			"For an existing local dependent Parameter, omit data.value: its DataVariant stores the Dependency binding, not a ScalarType value. apply_element_spec rejects data.value for this state.",
			"Dependency is not part of apply_element_spec JSON. To make a parameter dependent, call set_element_dependency after the target parameter exists.",
			"When dependencyFormula is provided to set_element_dependency, dependencyMappings is mandatory unless bindingPolicy=autoExactName is paired with explicit dependencyFormals. autoExactName maps only a uniquely resolvable same-named Parameter, Constant, or System Constant; never infer mappings from formula text, never infer formals by tokenizing it, and never use fuzzy matching.",
			"Select the affected DataVariant set explicitly. Never treat an omitted or ambiguous variant selection as all variants; if the operation cannot express the requested variant scope, stop at preflight rather than write.",
			"When changing dependent to independent, provide an explicit restoration source for every affected DataVariant: a snapshot, an explicit value, or an explicit ASCET default. Do not silently clear the formula, restore zero, or choose an implicit default.",
			"Method return values and method arguments are not apply_element_spec elements. For method return or arguments such as calc/p_CmpF_MC1, use set_method_signature before writing method code.",
			"Executed apply_element_spec writes always perform mandatory automatic action-specific readback verification. Inspect the returned verification feedback; do not request or skip verification through tool parameters.",
			"If required create fields are unknown, stop at plan and inspect the live component or ask for the missing value. For intent=patch, provide only the intended changes and let plan merge them with the live snapshot.",
		],
		fewShots: [
			'apply_element_spec: ascet_edit({action:"apply_element_spec",componentPath:"F/C",intent:"create",elements:[{role:"providerExportedParameter",name:"P",modelType:"cont",unit:"",comment:"Provider output",calibration:false,range:{mode:"none"},data:{mode:"ascetDefault"},implementation:{mode:"ascetDefault"}}]})',
		],
		tags: ["write", "element"],
	},
	{
		id: "ascet_edit.dependent_parameter",
		tool: "ascet_edit",
		action: "dependent_parameter",
		profiles: ["write-preflight"],
		summary: "Write dependent local parameters only after every dependency target is resolved.",
		rules: [
			"Before creating or updating a dependent Local Parameter, resolve every dependency mapping target with ascet_get.tree, ascet_get.elements, and exact live binding/reference reads as needed.",
			"For an Imported Parameter target, resolve the authoritative same-named Exported Parameter provider and verify compatibility; do not require an Exported provider for Constant or System Constant targets.",
			"If any target or required provider is unknown, ambiguous, or not found, stop at preflight and gather evidence before writing.",
			"Dependency mappings may target an existing Parameter, Constant, or System Constant. Resolve every target's live kind, scope, name, and OID before writing; do not assume that a mapping target is Imported.",
			"If a mapping target is an Imported Parameter, additionally resolve the authoritative same-named Exported Parameter provider and verify the Imported/Exported compatibility. Do not apply this provider-chain requirement to Constant or System Constant targets.",
			"The Local Dependent Parameter may have a local name, but its formula mapping must be explicit and must resolve to the declared Parameter, Constant, or System Constant targets.",
			"When creating a dependent Local Parameter from an exported provider, align metadata from the authoritative provider, not from the bridge Imported Parameter, unless the user explicitly requests a transform.",
			"Imported Parameters are bridge elements and normally require no independent implementation configuration. Do not invent implementation range, formula, calibration, or limits for Imported Parameters unless project rules explicitly require it.",
			"Do not create an exported parameter inside the consuming component merely to satisfy a dependency relationship.",
			"Use set_element_dependency to set or clear the dependency flag of an existing local parameter and to set that local parameter's dependency formula.",
			"set_element_dependency does not create local, imported, or exported elements. Use apply_element_spec first when any of those elements are missing.",
			"dependencyFormula is the expression stored on the dependent local parameter. It is not an implementation conversion formula and is not a project formula.",
			'When dependencyFormula is provided, pass dependency="dependent". Do not pass dependencyFormula together with dependency="independent".',
			"Referenced Parameters, Constants, and System Constants must already exist and be resolvable in the requested scope. Do not create mapping targets, imported parameters, exported parameters, or provider components inside set_element_dependency.",
			"Select the affected DataVariant set explicitly; different DataVariants may use different mappings, and omitted selection must not silently mean all.",
			"When changing dependent to independent, require an explicit restoration source for every affected DataVariant: a snapshot, an explicit value, or an explicit ASCET default. Do not silently clear the formula or restore zero.",
			"Executed set_element_dependency writes always perform mandatory automatic action-specific readback verification. After a verified write, do not issue a redundant live read; treat previously stored observations for the affected target as invalidated and request a fresh bounded ascet_get result when structure is needed again.",
		],
		fewShots: [
			'set_element_dependency: ascet_edit({action:"set_element_dependency",targetPath:"F/C",elementName:"K",dependency:"dependent",variantPolicy:"default"})',
		],
		tags: ["write", "dependency", "provider-discovery"],
	},
	{
		id: "ascet_batch_write.batch_write",
		tool: "ascet_batch_write",
		action: "batch_write",
		profiles: ["batch-write"],
		summary: "Hidden batch-write instruction.",
		rules: [
			"Batch write is hidden by default and must not be injected into public prompt assembly unless explicitly enabled.",
		],
		hidden: true,
		tags: ["hidden", "batch"],
	},
] as const satisfies readonly AscetActionInstruction[];
