import { compactExamplesForTool } from "../_shared/action-examples.ts";

export const ascetReadPrompt = {
	promptSnippet: "Use ascet_read after resolving the ASCET component path.",
	promptGuidelines: [
		"Use read for lean summaries, or read with methodName for one method body.",
		"Use read_method_signature to verify a method's primitive return type and arguments after create_method or set_method_signature.",
		"Use read_code when the user explicitly needs code text; this maps to logical AscetReadCode.",
		"Use read_block_diagram only for resolved class/module targets with a BDE/block-diagram surface; for ESDL text components prefer read_code or read_implementation.",
		"Treat an empty block-diagram payload as an empty diagram, not evidence that the component is missing.",
		"Use read_state_machine_flow only for resolved StateMachine targets; for classes/modules use read, read_code, or read_implementation.",
		"Use read_code section=header or external-c only for C module targets; for ESDL class/module method code pass methodName with section=body or all.",
		"read_block_diagram accepts timeoutMs in milliseconds and defaults to 60000.",
		"Use read_dependent_chain when the user asks which exported or global parameter a local dependent parameter depends on.",
		"Use read_element_dependency when the user asks for the current dependency flag, stored formula, or supported write plan for one element without provider discovery.",
		"Use read_dependent_chain to analyze a Local Parameter -> Imported Parameter -> Exported Parameter chain.",
		"Use read_dependent_chain to inspect the dependency flag, dependency formula, formula references, imported-parameter mappings, and exported-provider chain for a local dependent parameter.",
		"Use read_element_dependency before set_element_dependency when you need the current dependency flag or formula for the target element.",
		"Use read_dependent_chain before set_element_dependency when you need to know the current provider chain.",
		"Use read_element_dependency after set_element_dependency to verify the local dependency flag and formula; use read_dependent_chain when provider-chain consistency also matters.",
		"The formula reported by read_dependent_chain is the local dependent parameter expression. It is not an implementation conversion formula and is not a project formula.",
		"Dependent parameter provider discovery is a coordinated workflow: first call read_dependent_chain with componentPath/dependentElement and a bounded providerScopePath when known; if provider discovery is incomplete or ambiguous, coordinate ascet_search and ascet_explore before concluding.",
		"The Imported Parameter in the consuming component and the Exported Parameter in the provider component must have the same name. Search provider candidates by the Imported Parameter name, not by the Local Dependent Parameter name unless they are identical.",
		"Only scope=Exported elements are valid provider candidates. Local or Imported same-name elements may be diagnostic clues, but they are not exported-provider evidence.",
		"When search_elements supports scope filtering, constrain provider searches to scope=Exported. If not, post-filter results and keep only elements whose scope is Exported.",
		"Common exported parameter providers are feature-scoped parameter classes such as _Calibration ... parameter, _Constant ... parameter, Calibration ... Parameter, Constant ... Parameter, or other feature-specific ... parameter classes.",
		"If read_dependent_chain reports export_not_found, export_ambiguous, provider_candidate_limit_exceeded, or complete=false, treat that as evidence requiring scoped recursive provider discovery.",
		"After selecting a provider candidate, call read_dependent_chain again with exporterComponentPath as a verification constraint. Do not treat search_elements alone as complete dependency-chain proof.",
		"Imported Parameters are binding bridge elements and normally keep default/generated implementation. The authoritative metadata source is the same-named Exported Parameter.",
		"Do not require the user to know exporterComponentPath. Prefer calling read_dependent_chain with componentPath and dependentElement only, and let the tool discover the imported parameter, exported parameter, and provider component.",
		"If exporterComponentPath is known, pass it only as a verification constraint.",
		"If the user provides a provider scope, feature scope, or search scope, pass it as providerScopePath to constrain exported parameter/provider discovery.",
		"Use read_dependent_chain as evidence when designing an analogous Local Parameter -> Imported Parameter -> Exported Parameter chain.",
		"When read_dependent_chain returns complete=false and issues[], treat them as diagnostic evidence. Do not invent missing provider paths, exported parameters, or default parameter values.",
		...compactExamplesForTool("ascet_read"),
	],
} as const;
