import { compactExamplesForTool } from "../_shared/action-examples.ts";

export const ascetWritePrompt = {
	promptSnippet: "Prepare or confirm one ASCET write action such as create, delete, set code, or apply spec.",
	promptGuidelines: [
		"By default this tool returns a non-error preflight outcome and does not write.",
		"Set executeWrite=true only when the user explicitly asks to apply the write; PI still requires confirmation.",
		"After create_component, inspect expectedDefaultScaffold.defaultEntryMethod as an unverified hint for the likely initial method.",
		"Before create_method, determine the target component kind. In v1, methodKind is constrained by component kind: class supports only abstract; module supports only process; statemachine supports only action, condition, or trigger.",
		"When methodKind is omitted for create_method, componentKind=class defaults to abstract and componentKind=module defaults to process. For statemachine targets, choose action, condition, or trigger explicitly.",
		"Do not create class methods with methodKind=process/action/condition/trigger. For ESDL Class components, create abstract first, then use set_method_signature for return/arguments and set_method_code for the body. Do not claim the method is concrete unless readback proves MethodKind changed.",
		"When component kind is unknown, inspect the target before executeWrite=true. A preflight result without component kind is not proof that the requested methodKind can be applied.",
		"For method bodies on Class or Module components, use set_method_code. Use set_module_code only for module text-code surfaces such as set-method, set-header, or set-external-c-code. Use set_state_machine_code for state-machine triggers, state bodies, transition bodies, bindings, and start-state changes.",
		"Use set_method_signature after create_method and before method body writes when the method body returns a value or reads method arguments; do not use apply_element_spec for method return or argument declarations.",
		"Use set_method_signature.arguments for primitive method inputs such as p_CmpF_MC1 before writing ESDL code that references them, and verify readback. If set_method_signature reports unsupported_method_kind, stop and report that the current method cannot accept primitive signature edits through this path.",
		"For apply_element_spec, treat specFile as a structured ASCET element-spec JSON artifact, not just a file path.",
		"Before creating an apply_element_spec specFile, derive element metadata from read_element_catalog, search_elements, preview_children, or explicit user requirements. Do not guess modelType, scope, range, implementation type, formula, calibration, or dependency.",
		"For apply_element_spec primitive elements, variable/parameter/array specs must include name, kind, modelType, and scope. Use concrete modelType values such as cont, log, sdisc, or udisc; do not use ambiguous disc.",
		'For apply_element_spec, a cont variable physical-range example is {"elements":[{"name":"Speed","kind":"variable","modelType":"cont","scope":"exported","physicalRange":{"min":0,"max":8000},"unit":"rpm","calibration":true,"data":{"value":0},"impl":{"valueType":"uint16","formula":"ident","limitAssignments":true}}]}.',
		'For apply_element_spec, an implementation-range example is {"elements":[{"name":"SpeedImpl","kind":"variable","modelType":"cont","scope":"exported","unit":"rpm","calibration":true,"data":{"value":0},"impl":{"valueType":"uint16","implementationRange":{"min":0,"max":8000},"formula":"ident","limitAssignments":true}}]}.',
		"For apply_element_spec, mode=restore updates/restores the supplied spec but does not remove missing elements unless deleteMissing=true is set.",
		"For apply_element_spec, physicalRange and impl.implementationRange are mutually exclusive. Choose exactly one range source per element; do not put both in the same spec element.",
		"For apply_element_spec exported/local parameters, when writing physicalRange or impl.implementationRange, use impl.limitAssignments=true; do not set it false on parameter range writes.",
		"For apply_element_spec imported parameters, create them only in the consuming/importing component and use the same name as the exported parameter they import.",
		'For imported parameters, specFile must be minimal: name, kind:"parameter", modelType, and scope:"imported". Do not set data.value, impl, physicalRange, impl.implementationRange, impl.limitAssignments, calibration, memory, or dependency fields for imported parameters.',
		"Before creating an imported parameter, verify or create the matching exported parameter in the provider component or project context. Imported parameter names must match their exported counterpart.",
		"Imported parameters are not made dependent directly. Dependency is determined by the exported counterpart or by a local dependent parameter chain; do not call set_element_dependency on an imported parameter.",
		"If the exported counterpart is unknown, ambiguous, or not found, stop at preflight and inspect provider candidates instead of creating a guessed imported parameter.",
		"Dependency is not part of apply_element_spec JSON. To make a parameter dependent, call set_element_dependency after the target parameter exists.",
		"Method return values and method arguments are not apply_element_spec elements. For method return or arguments such as calc/p_CmpF_MC1, use set_method_signature before writing method code.",
		"Use verifyReadback=true for apply_element_spec unless the user explicitly asks to skip verification.",
		"If required primitive fields are unknown, stop at preflight and inspect the live component or ask for the missing field; do not write a partial specFile.",
		"When creating a parameter dependency chain, follow ASCET parameter ownership rules.",
		"Create exported parameters in the provider component or in an approved shared parameter provider path.",
		"Do not create an exported parameter inside the current consuming component merely to make a local parameter dependency possible.",
		"Group exported parameters by feature/function.",
		"Within each feature/function group, separate calibration parameters from non-calibration parameters.",
		"Choose the exported parameter provider by function type: calibration parameters belong in the feature's Calibration parameter class; fixed non-calibration parameters belong in the feature's Constant parameter class.",
		"Before creating or updating a dependent Local Parameter, resolve the authoritative same-named Exported Parameter provider with read_dependent_chain or the coordinated read/search/explore workflow.",
		"Do not create a new Exported Parameter if a same-named Exported Parameter already exists in a feature _Calibration, _Constant, or other parameter provider class.",
		"Do not bind to a provider candidate unless the matching element is scope=Exported.",
		"Create local parameters inside the consuming component.",
		"When creating a new dependent local parameter, keep its metadata aligned with the exported parameter unless the user explicitly requests a transform. This includes model type/display type, unit, physical range, implementation value type, implementation range, formula, dimension, and calibration classification.",
		"Calibration is an apply_element_spec primitive field; use boolean calibration only for variable, parameter, array, enumeration, and table elements, and verify readback before claiming it.",
		"For apply_project_formula, linear formulas may read back normalized as offset + factor * phys; compare the semantic factor/offset, not the raw input string.",
		"For set_module_code, provide section/operation as one of set-method, set-header, or set-external-c-code.",
		"For set_state_machine_code, use one of: set-method, set-state-entry-esdl, set-state-exit-esdl, set-state-static-esdl, bind-state-entry-method, bind-state-exit-method, bind-state-static-method, set-transition-condition-esdl, set-transition-action-esdl, bind-transition-condition-method, bind-transition-action-method, set-start-state.",
		"Use set_element_dependency to change the dependency flag after the target ASCET element already exists.",
		"Use set_element_dependency to set or clear the dependency flag of an existing local parameter and to set that local parameter's dependency formula.",
		"dependencyFormula is the expression stored on the dependent local parameter. It is not an implementation conversion formula and is not a project formula.",
		'When dependencyFormula is provided, pass dependency="dependent". Do not pass dependencyFormula together with dependency="independent".',
		'Use dependencyMappings to map formula formal/reference names to existing imported parameters in the consuming component. For example, dependencyMappings: {"K_Factor":"K_Factor"} means the formula reference K_Factor uses the imported parameter K_Factor.',
		"Referenced imported parameters must already exist in the consuming component. Do not create imported parameters, exported parameters, or provider components inside set_element_dependency.",
		"Do not use apply_element_spec.impl.formula, apply_project_formula, or project formula tools to set a dependent local parameter expression.",
		"Use read_element_dependency before writing when the current dependency flag or formula is unknown; use read_dependent_chain when imported parameter mapping or exported provider evidence is also needed.",
		'For a new dependent local parameter: create or verify the exported parameter in the provider component or approved parameter provider path, create or verify the same-named imported parameter in the consuming component, keep the imported parameter at default initialization, create the local parameter inside the consuming component with metadata aligned to the exported parameter unless a transform was requested, then call set_element_dependency on the local parameter with dependency="dependent" and verifyReadback=true.',
		"When dependencyFormula references a parameter, dependencyMappings must map formula names to existing Imported Parameter names in the consuming component.",
		"The Imported Parameter and Exported Parameter must have the same name. The Local Dependent Parameter may differ, but its formula mapping must resolve through Imported Parameter names.",
		"When creating a dependent Local Parameter from an Exported Parameter, align metadata from the Exported Parameter, not from the Imported Parameter, unless the user explicitly requests a transform.",
		"Imported Parameters are bridge elements and normally require no independent implementation configuration. Do not invent implementation range, formula, calibration, or limits for Imported Parameters unless project rules explicitly require it.",
		"If multiple exported providers exist, stop with ambiguity evidence unless one provider is selected by exact same name, scope=Exported, same feature scope, provider role, and matching metadata.",
		"For an existing local parameter, use read_element_dependency, read_dependent_chain, preview_children, search_elements, or set_element_dependency dryRun=true to gather evidence when the target is unclear.",
		'For one local parameter inside one component, use set_element_dependency with targetKind="component" and match="exact". If the target scope is unclear, run set_element_dependency with dryRun=true before writing.',
		"Do not call set_element_dependency before the target local parameter exists.",
		"Do not create an exported parameter inside the consuming component merely to satisfy a dependency relationship.",
		"When the intent is to make a consuming component's local parameter dependent, do not call set_element_dependency on the exported parameter.",
		"Use verifyReadback=true unless the user explicitly asks to skip readback.",
		...compactExamplesForTool("ascet_write"),
	],
} as const;
